//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IddaaSimuService
{
    using System;
    using System.Collections.Generic;
    
    public partial class match
    {
        public int id { get; set; }
        public string evsahibi { get; set; }
        public string konuk { get; set; }
        public long iddaakod { get; set; }
        public System.DateTime startDate { get; set; }
        public System.TimeSpan startTime { get; set; }
        public double ms1 { get; set; }
        public double ms2 { get; set; }
        public double msx { get; set; }
        public double kgvar { get; set; }
        public double kgyok { get; set; }
        public double cifte1x { get; set; }
        public double cifte12 { get; set; }
        public double cifte2x { get; set; }
        public double ilkg1 { get; set; }
        public double ilkg2 { get; set; }
        public double ilkgolmaz { get; set; }
        public double alt05 { get; set; }
        public double ust05 { get; set; }
        public double alt15 { get; set; }
        public double ust15 { get; set; }
        public double alt25 { get; set; }
        public double ust25 { get; set; }
        public double alt35 { get; set; }
        public double ust35 { get; set; }
        public double alt45 { get; set; }
        public double ust45 { get; set; }
        public double tgol01 { get; set; }
        public double tgol23 { get; set; }
        public double tgol45 { get; set; }
        public double tgol6arti { get; set; }
        public double ilkyari1 { get; set; }
        public double ilkyari2 { get; set; }
        public double ilkyarix { get; set; }
        public double ikinciyari1 { get; set; }
        public double ikinciyari2 { get; set; }
        public double ikinciyarix { get; set; }
        public double ilkkorner1 { get; set; }
        public double ilkkorner2 { get; set; }
        public double ilkkorner0 { get; set; }
        public double kirmizikartvar { get; set; }
        public double kirmizikartyok { get; set; }
        public double mskor10 { get; set; }
        public double mskor20 { get; set; }
        public double mskor21 { get; set; }
        public double mskor30 { get; set; }
        public double mskor31 { get; set; }
        public double mskor32 { get; set; }
        public double mskor40 { get; set; }
        public double mskor41 { get; set; }
        public double mskor42 { get; set; }
        public double mskor50 { get; set; }
        public double mskor51 { get; set; }
        public double mskor60 { get; set; }
        public double mskor00 { get; set; }
        public double mskor11 { get; set; }
        public double mskor22 { get; set; }
        public double mskor33 { get; set; }
        public double mskor01 { get; set; }
        public double mskor02 { get; set; }
        public double mskor12 { get; set; }
        public double mskor03 { get; set; }
        public double mskor13 { get; set; }
        public double mskor23 { get; set; }
        public double mskor04 { get; set; }
        public double mskor14 { get; set; }
        public double mskor24 { get; set; }
        public double mskor05 { get; set; }
        public double mskor15 { get; set; }
        public double mskor06 { get; set; }
        public double mskorothers { get; set; }
    }
}
